- src: https://github.com/geerlingguy/ansible-role-apache.git
  path: roles

- src: https://github.com/vbrinza/ansible-role-zabbix-server.git
  path: roles

- src: https://github.com/vbrinza/ansible-role-mysql.git
  path: roles

- src: https://github.com/geerlingguy/ansible-role-php.git
  path: roles

- src: https://github.com/vbrinza/ansible-role-zabbix-agent.git
  path: roles

- src: https://github.com/vbrinza/ansible-role-common.git
  path: roles

- src: https://github.com/vbrinza/ansible-role-grafana.git
  path: roles

- src: https://github.com/vbrinza/ansible-role-zabbixweb.git
  path: roles
